apiVersion: v1
kind: Service
metadata:
  name: express-sqlite-loadbalancer-service
  labels:
    app: express-sqlite-app
spec:
  selector:
    app: express-sqlite-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
